const locations = [
  'Dirtmouth',
  'Fungal Wastes',
  'Colosseum of Fools',
  'Fog Canyon',
  'City of Tears',
  'Forgotten Crossroads',
  'Stag Station',
  'Royal Waterways',
  'Howling Cliffs',
  'Kingdom\'s Edge',
  'Greenpath',
  'All Major Areas',
  'Temple of the Black Egg',
  'Resting Grounds',
  'Beast\'s Den',
  'Deepnest',
  'Queen\'s Gardens',
  'Ancestral Mound',
  'White Palace ',
  'Lake of Unn',
  'Shrine of Believers',
  'Queen\'s Station',
  'Junk Pit'
]